# Generated by Django 4.2 on 2023-05-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_userinfo'),
    ]

    operations = [
    ]
