# Generated by Django 4.2 on 2023-05-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20230503_1912'),
    ]

    operations = [
    ]
