# Generated by Django 4.2 on 2023-05-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20230503_1914'),
    ]

    operations = [
    ]
