# Generated by Django 4.2 on 2023-05-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20230503_1917'),
    ]

    operations = [
    ]
