# Generated by Django 4.2 on 2023-05-04 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20230503_1939'),
    ]

    operations = [
    ]
